name: ScalaLoader
version: ${project.version}
main: xyz.janboerman.scalaloader.ScalaLoader
load: STARTUP
author: Jannyboy11
description: Provides scala runtime classes
api-version: 1.13

commands:
  resetScalaUrl:
    usage: "/<command> all|[<scala version>]"
    description:
      - Resets the config URL of the built-in scala version.
      - Useful if you overwrote some of the urls.
      - If 'all' is provided as a scala version, this command resets the URLs of all the built-in scala versions.
    permission: scalaloader.resetscalaurls

permissions:
  scalaloaders.resetscalaurls:
    description: Allows users to reset the scala url configs.
    default: OP
